dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
  matrix:
    - SCRIPT="run-e2e-tests --fast"
    - SCRIPT="check-deploy --dry-run"    
before_install:
  - npm install -g gulp --no-optional
  - if [[ "$SCRIPT" == "run-e2e-tests --fast" ]]; then npm install -g protractor --no-optional; fi
  - if [[ "$SCRIPT" == "check-deploy --dry-run" ]]; then git clone https://github.com/angular/angular.git ../angular; fi
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --no-optional
  - if [[ "$SCRIPT" == "run-e2e-tests --fast" ]]; then npm install --prefix public/docs/_examples; fi
  - if [[ "$SCRIPT" == "run-e2e-tests --fast" ]]; then gulp add-example-boilerplate; fi
script:
  - gulp $SCRIPT